-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 01:29:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `apellido` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anuncios` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL,
  `vigente` BOOLEAN NOT NULL,
  `usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`),
  INDEX `fk_anuncios_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_anuncios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comisiones` (
  `id` INT NOT NULL,
  `anio` TINYINT UNSIGNED NOT NULL,
  `comision` TINYINT UNSIGNED NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anuncios.comisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anuncios.comisiones` (
  `anuncios_id` INT NOT NULL,
  `comisiones_id` INT NOT NULL,
  PRIMARY KEY (`anuncios_id`, `comisiones_id`),
  INDEX `fk_anuncios_has_comisiones_comisiones1_idx` (`comisiones_id` ASC),
  INDEX `fk_anuncios_has_comisiones_anuncios_idx` (`anuncios_id` ASC),
  CONSTRAINT `fk_anuncios_has_comisiones_anuncios`
    FOREIGN KEY (`anuncios_id`)
    REFERENCES `mydb`.`anuncios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncios_has_comisiones_comisiones1`
    FOREIGN KEY (`comisiones_id`)
    REFERENCES `mydb`.`comisiones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
